console.log("test1");
console.log("test2");
console.log("=====");
console.log("-wwwwwwwwwww");
console.log("-wwwwwwwwwwwwwwwww>");
console.log("----...");
console.log("-wwwwwwwwwwwwwwwww>");
console.log("-wwwwwwwwwwwwwwwww>");
console.log("-wwwwwwwwwwwwwwwww>");
console.log("-wwwwwwwwwwwwwwwww>");
console.log("-wwwwwwwwwwwwwwwww>");
console.log("-wwwwwwwwwwwwwwwww>");
console.log("-wwwwwwwwwwwwwwwww>");
console.log("-wwwwwwwwwwwwwwwww>");
console.log("-wwwwwwwwwwwwwwwww>");
console.log("-wwwwwwwwwwwwwwwww>");
console.log("-wwwwwwwwwwwwwwwww>");
console.log("-wwwwwwwwwwwwwwwww>");
console.log("-wwwwwwwwwwwwwwwww>")
w

